'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute()>
Namespace DXSample
	#Region "Contexts"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	Partial Public Class TestDBEntities
		Inherits ObjectContext
		#Region "Constructors"

		''' <summary>
		''' Initializes a new TestDBEntities object using the connection string found in the 'TestDBEntities' section of the application configuration file.
		''' </summary>
		Public Sub New()
			MyBase.New("name=TestDBEntities", "TestDBEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new TestDBEntities object.
		''' </summary>
		Public Sub New(ByVal connectionString As String)
			MyBase.New(connectionString, "TestDBEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new TestDBEntities object.
		''' </summary>
		Public Sub New(ByVal connection As EntityConnection)
			MyBase.New(connection, "TestDBEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		#End Region

		#Region "Partial Methods"

		Partial Private Sub OnContextCreated()
		End Sub

		#End Region

		#Region "ObjectSet Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property TestTables() As ObjectSet(Of TestTable)
			Get
				If (_TestTables Is Nothing) Then
					_TestTables = MyBase.CreateObjectSet(Of TestTable)("TestTables")
				End If
				Return _TestTables
			End Get
		End Property
		Private _TestTables As ObjectSet(Of TestTable)

		#End Region

		#Region "AddTo Methods"

		''' <summary>
		''' Deprecated Method for adding a new object to the TestTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
		Public Sub AddToTestTables(ByVal testTable As TestTable)
			MyBase.AddObject("TestTables", testTable)
		End Sub

		#End Region

	End Class

	#End Region

	#Region "Entities"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="TestDBModel", Name:="TestTable"), Serializable(), DataContractAttribute(IsReference:=True)> _
	Partial Public Class TestTable
		Inherits EntityObject
		#Region "Factory Method"

		''' <summary>
		''' Create a new TestTable object.
		''' </summary>
		''' <param name="text">Initial value of the Text property.</param>
		Public Shared Function CreateTestTable(ByVal text As Global.System.String) As TestTable
			Dim testTable As New TestTable()
			testTable.Text = text
			Return testTable
		End Function

		#End Region

		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property Text() As Global.System.String
			Get
				Return _Text
			End Get
			Set(ByVal value As System.String)
				If _Text <> value Then
					OnTextChanging(value)
					ReportPropertyChanging("Text")
					_Text = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("Text")
					OnTextChanged()
				End If
			End Set
		End Property
		Private _Text As Global.System.String
		Partial Private Sub OnTextChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnTextChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Number() As Global.System.Int32?
			Get
				Return _Number
			End Get
			Set(ByVal value? As System.Int32)
				OnNumberChanging(value)
				ReportPropertyChanging("Number")
				_Number = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Number")
				OnNumberChanged()
			End Set
		End Property
		Private _Number? As Global.System.Int32
		Partial Private Sub OnNumberChanging(ByVal value? As Global.System.Int32)
		End Sub
		Partial Private Sub OnNumberChanged()
		End Sub

		#End Region


	End Class

	#End Region


End Namespace
